### ISSUE TITLE
rename compare method to something more specific

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/string-compare#1]
@crain9412 `computeDistance`?

**Comment by crain9412** [comment]
That seems fine to me

**Comment by fitzyjoe** [comment]
Have you considered implementing java.util.Comparator<String> for this?

**Comment by kevinmichaelchen** [comment]
The method signature in Comparator (`int compare(T o1, T o2)`) is pretty much exactly what I want, but Comparator seems to be more about "ordering" (see [Javadocs](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html))
> A comparison function, which imposes a total ordering on some collection of objects
