### ISSUE TITLE
do not use static methods?

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/string-compare#2]
@fitzyjoe, after your research into testing static methods, do you have any opinions on whether to use static methods or instance methods?
```java
StringComparer.compare("a", "b");
```
vs
```java
StringComparer sc = new StringComparer();
sc.compare("a", "b");
```

**Comment by fitzyjoe** [comment]
Static is the way to go for this.  The two options I was considering was
between

1. having a class with all static methods; and

public final class StringComparer
{
   private StringComparer()
   {

   }

   public static int compare(String a, String b)
   {
      // do something
      return 0;
   }
}


2. a singleton with all non-static methods.

public class StringComparer
{
   protected static StringComparer instance;

   static
   {
      instance = new StringComparer();
   }

   protected StringComparer()
   {

   }

   public static StringComparer getInstance()
   {
      return instance;
   }

   public int compare(String a, String b)
   {
      // do something
      return 0;
   }
}


So you would use it like this:

StringComparer.getInstance().compare("a", "b");


This leaves the door open for inheritance.  And compared to your example,
saves you from constructing an object.

However, the better practice is to *have a class with all static methods*.
You don't have to construct the object at all and it's arguably clearer to
the devs that the object contains no state.  Both seem equivalent to test,
with the exception of the getInstnace() method.

I think it's best not to keep any state in a class that has any public
static methods.

In the Thumbnailer project, here's what I used to ensure that my classes
that contained all static methods were properly formed.  In the class
AssertTesla (could use a better name) I have a method
called assertUtilityClassWellDefined which uses reflection to inspect the
provided class and ensures:

The class must be final
There must be only one constructor
The constructor must be private
All of the methods are static

And while it performs these assertions, it instantiates the private
constructor to hit the code coverage.

One more thing... this does not really influence the issue, but you might
be interested to know: Instances of objects take up memory on the heap, but
static methods are part of the class definition and so only take up memory
on the stack/perm gen.

 -Joe

**Comment by kevinmichaelchen** [comment]
>This leaves the door open for inheritance.  And compared to your example,
saves you from constructing an object.

OTOH, for Spring-users, Spring is essentially creating a singleton when a service autowires a bean, so the user is saved from instantiating a new object every time.
```java
@Configuration
class StringComparerConfiguration {

  @Bean
  public StringComparer stringComparer() {
    return new StringComparer();
  }
}

@Service
class StringCompareService {

  @Autowired
  private StringComparer stringComparer;

  public boolean areSimilar(String a, String b) {
    return stringComparer.compare(a, b) < 32;
  }
}
```

**Comment by fitzyjoe** [comment]
I had written almost the identical sentence in my initial response!  And
then I deleted it before I submitted it because I don't see an advantage to
autowiring the StringComparer rather than calling the class with the static
methods directly.  Mocking the static methods requires PowerMock rather
than mockio... but doesn't seem like a big difference.  What do you think
are the trade-offs here?

**Comment by kevinmichaelchen** [comment]
some cons of singletons:
* autowired fields stand out more; direct calls to static methods can be buried

some pros of beans:
* if `StringComparer` were an interface, we could support autowiring different implementations (i.e., an alternative to Nilsimsa+Levenshtein)

of course, we could probably publish `StringComparer` and `StringComparerSingleton`
